version: '3'
services:
  cups:
    image: stgriesb/cups
    container_name: cups
    network_mode: host
    restart: unless-stopped
    ports:
      - '631:631/tcp'
    volumes:
      - '${VOLUME}/var-spool:/var/spool'
      - '${VOLUME}/var-log:/var/log/cups'
      - '${VOLUME}/var-cache:/var/cache/cups'
      - '${VOLUME}/etc-cups:/etc/cups'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      CUPS_ADMIN_USERNAME: ${CUPS_ADMIN_USERNAME}
      CUPS_ADMIN_PASSWORD: ${CUPS_ADMIN_PASSWORD}
