version: '3'
services:
  cups:
    image: cups-avahi
    container_name: cups-avahi
    network_mode: host
    restart: always
    ports:
      - '631:631/tcp'
    volumes:
      - '/docker/cups/cfg/spool:/var/spool:rw'
      - '/docker/cups/cfg:/etc/cups:rw'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      CUPS_ADMIN_USERNAME: 'USERNAME'
      CUPS_ADMIN_PASSWORD: 'PASSWORD'
